# retrieve drug labels
api_key: "niBOH6xHMCgaizNvXzBuEXWXnkAT3kWcheuKgoht"
batch_size: 100
max_requests_per_min: 10
checkpoint_file: "../data/checkpoint_ndc.json"
output_dir: "../data/fda_drug_labels"
allowed_product_types:
  - HUMAN PRESCRIPTION DRUG
  - HUMAN OTC DRUG
  - HUMAN PRESCRIPTION BIOLOGIC
essential_fields:
  - generic_name
  - brand_name
  - product_ndc
  - route
  - dosage_form
  - substance_name
  - manufacturer_name
  - purpose
  - indications_and_usage
  - description
  - clinical_pharmacology
  - contraindications
  - warnings
  - adverse_reactions
  - drug_interactions

# extract indications from free text
disease_dict_path: "../data/reference/diseases.json"
label_input_dir: "../data/fda_drug_labels"
drug_indication_output_dir: '../data/indication_extracts'
